#primera figura
print(10*"*")
print(4*"*"+2*" "+4*"*")
print(3*"*"+4*" "+3*"*")
print(2*"*"+6*" "+2*"*")
print(1*"*"+8*" "+1*"*")
print(1*"*"+8*" "+1*"*")
print(2*"*"+6*" "+2*"*")
print(3*"*"+4*" "+3*"*")
print(4*"*"+2*" "+4*"*")
print(10*"*")
#segunda figura
print("*"+"       "+"*")
print(2*"*"+"     "+ 2*"*")
print("*"+" "+"*"+"   "+"*"+" "+"*")
print("*"+"  "+"*"+" "+"*"+"  "+"*")
print("*"+"   "+"*"+"   "+"*")
print("*"+"  "+"*"+" "+"*"+"  "+"*")
print("*"+" "+"*"+"   "+"*"+" "+"*")
print(2*"*"+"     "+ 2*"*")
print("*"+"       "+"*")
#tercera figura
print("    "+"*")
print("   "+3*"*")
print("  "+5*"*")
print(" "+7*"*")
print(9*"*")
print(" "+7*"*")
print("  "+5*"*")
print("   "+3*"*")
print("    "+"*")
#curta figura
print("*"+12*" "+"*")
print(2*"*"+10*" "+2*"*")
print(3*"*"+8*" "+3*"*")
print(4*"*"+6*" "+4*"*")
print(5*"*"+4*" "+5*"*")
print(6*"*"+2*" "+6*"*")
print(14*"*")
#quinta figura
print(10*" "+"*")
print(9*" "+3*"*")
print(8*" "+5*"*")
print(7*" "+7*"*")
print(6*" "+9*"*")
print(5*" "+11*"*")
print(4*" "+13*"*")
print(3*" "+15*"*")
print(2*" "+17*"*")
print(1*" "+19*"*")
print(21*"*")
print(7*" "+7*"*")
print(6*" "+9*"*")
print(5*" "+11*"*")
print(4*" "+13*"*")
print(3*" "+15*"*")
print(2*" "+17*"*")
print(" "+19*"*")
print(8*" "+5*"*")
print(8*" "+5*"*")
print(8*" "+5*"*")



